apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-backend
  description: "Customer Backend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-backend.yaml"
spec:
  type: service
  lifecycle: production
  owner: dev-team
  dependsOn:
    - resource:database/customer_database
    - resource:S3-bucker/images_s3
  providesApis:
    - customer_api
   