apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: customer_database
  description: "Customer Data"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/database.yaml"
spec:
  type: database
  owner: dev-team