apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer_api
  description: "Get Customer Images API"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-grpc-api.yaml"
spec:
  type: grpc
  lifecycle: production
  owner: dev-team
  definition: |
    syntax = "proto3";
    package myorg.mygrpcapi;
    message MyRequest {
      string query = 1;
    }
    message MyResponse {
      string result = 1;
    }
    service MyGrpcApi {
      rpc MyMethod (MyRequest) returns (MyResponse);
    }